[workspace]
resolver = "3"
members = ["crates/usdcx-faucet", "crates/usdcx-relayer"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.90"
license = "MIT"

[workspace.dependencies]
miden-assembly = { version = "0.15", default-features = false, features = ["std"] }
miden-core = { version = "0.15", default-features = false, features = ["std"] }
miden-processor = { version = "0.23", default-features = false, features = ["std"] }
miden-protocol = { version = "0.15", default-features = false, features = ["std"] }
miden-standards = { version = "0.15", default-features = false, features = ["std"] }
miden-testing = { version = "0.15", default-features = false, features = ["std"] }
miden-tx = { version = "0.15", default-features = false, features = ["std"] }

usdcx-faucet = { path = "crates/usdcx-faucet" }

rand_chacha = "0.9"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
tracing = "0.1"
