[package]
name = "usdcx-relayer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "usdcx-relayer"
path = "src/main.rs"

[dependencies]
usdcx-faucet = { workspace = true }
miden-protocol = { workspace = true }
miden-standards = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
miden-testing = { workspace = true }
